## Before attempting to run please provide your API Token in the following variable. You can generate this from the Hub website: https://test.eodatahub.org.uk/workspaces/
@apiToken=<apiToken>

@scheme = https
@ades=dev3.eodatahub.org.uk/ades
@workspace = jlangstone-tpzuk
@stacKey = s3://workspaces-eodhp-dev3/jlangstone-tpzuk/commercial-data/collections/airbus_phr_data/items/DS_PHR1A_201203021558128_FR1_PX_W080S03_0221_01728.json
@commercialBucket = commercial-data-airbus
@productBundle = general_use
@pulsarUrl = pulsar://pulsar-broker.pulsar:6650
@workspaceBucket = workspaces-eodhp-dev3
@coordinates = [[[-8.04575859845228, 31.7018335608202], [-8.13085357903705, 31.6969488507275], [-8.1302277917, 31.6038867332], [-8.02977481420451, 31.5982362108166], [-7.95210682318346, 31.603078531553], [-7.9521185644, 31.6961852319], [-8.04575859845228, 31.7018335608202]]]
@licence = "standard"

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/airbus/ogc-api/processes/airbus-optical-adaptor HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###


# @name listProcesses
GET {{scheme}}://{{ades}}/airbus/ogc-api/processes HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name deployProcessJson
POST {{scheme}}://{{ades}}/airbus/ogc-api/processes HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json
Content-Type: application/cwl+yaml

< airbus-optical.cwl

###

# @name getDeployStatus
GET {{deployStatus}} HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/airbus/ogc-api/processes/airbus-optical-adaptor HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name executeProcess
POST {{scheme}}://{{ades}}/airbus/ogc-api/processes/airbus-optical-adaptor/execution HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {
    "workspace": "{{workspace}}",
    "workspace_bucket": "{{workspaceBucket}}",
    "commercial_data_bucket": "{{commercialBucket}}",
    "pulsar_url": "{{pulsarUrl}}",
    "product_bundle": "{{productBundle}}",
    "stac_key": "{{stacKey}}",
    "coordinates": "{{coordinates}}",
    "licence": "{{licence}}"
  }
}

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name getProcessingResults
GET {{executeStatus}}/results HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name undeployProcess
DELETE {{scheme}}://{{ades}}/airbus/ogc-api/processes/airbus-optical-adaptor HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name listJobs
GET {{scheme}}://{{ades}}/airbus/ogc-api/jobs HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

