## Before attempting to run please provide your API Token in the following variable. You can generate this from the Hub website: https://test.eodatahub.org.uk/workspaces/
@apiToken=<apiToken>

@scheme = https
@ades=dev.eodatahub.org.uk/ades
@username=airbus
@workspace = apalmer-tpzuk
@stacKey = s3://workspaces-eodhp-dev/apalmer-tpzuk/commercial-data/collections/airbus_sar_data/items/TDX-1_SC_S_scan_005R_80035_A12370838_22781.json
@commercialBucket = commercial-data-airbus
@productBundle = general_use

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/airbus-sar-adaptor HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###


# @name listProcesses
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json
Content-Type: application/cwl+yaml

< airbus-sar.cwl

###

# @name getDeployStatus
GET {{deployStatus}} HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/airbus-sar-adaptor HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name executeProcess
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/airbus-sar-adaptor/execution HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {
    "workspace": "{{workspace}}",
    "commercial_data_bucket": "{{commercialBucket}}",
    "product_bundle": "{{productBundle}}",
    "stac_key": "{{stacKey}}"
  }
}

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name getProcessingResults
GET {{executeStatus}}/results HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name undeployProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/airbus-sar-adaptor HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name listJobs
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/jobs HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###
