## Before attempting to run please provide your API Token in the following variable. You can generate this from the Hub website: https://test.eodatahub.org.uk/workspaces/
# AIRBUS
@apiToken=<apiToken>
# APALMER
#@apiToken=<apiToken>

@scheme = https
@ades=dev.eodatahub.org.uk/ades
@username=airbus
@workspace = apalmer-tpzuk
@stacKey = s3://workspaces-eodhp-dev/apalmer-tpzuk/commercial-data/collections/airbus_pneo_data/items/ACQ_PNEO3_05300415120321.json
@stacKey = [s3://workspaces-eodhp-dev/apalmer-tpzuk/commercial-data/collections/airbus_pneo_data/items/ACQ_CP_PNEO3_052307_0015052955_ST_0-27.json, s3://workspaces-eodhp-dev/apalmer-tpzuk/commercial-data/collections/airbus_pneo_data/items/ACQ_PNEO3_05230715052955.json]

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/airbus-optical-adaptor-multi HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###


# @name listProcesses
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json
Content-Type: application/cwl+yaml

< airbus-optical-multi.cwl

###

# @name getDeployStatus
GET {{deployStatus}} HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/airbus-optical-adaptor-multi HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name executeProcess
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/airbus-optical-adaptor-multi/execution HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {
    "workspace": "{{workspace}}",
    "stac_keys": [
      "s3://workspaces-eodhp-dev/apalmer-tpzuk/commercial-data/collections/airbus_pneo_data/items/ACQ_CP_PNEO3_052307_0015052955_ST_0-27.json",
      "s3://workspaces-eodhp-dev/apalmer-tpzuk/commercial-data/collections/airbus_pneo_data/items/ACQ_PNEO3_05230715052955.json",
      "s3://workspaces-eodhp-dev/apalmer-tpzuk/commercial-data/collections/airbus_pneo_data/items/ACQ_PNEO3_05230715052956.json"
    ]
  }
}

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name getProcessingResults
GET {{executeStatus}}/results HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name undeployProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/airbus-optical-adaptor-multi HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###

# @name listJobs
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/jobs HTTP/1.1
Authorization: Bearer {{apiToken}}
Accept: application/json

###
